### ISSUE TITLE
Selecting the local minima in ICL

### ISSUE THREAD

**Issue by Quantumstud** [quantitativeTEM/StatSTEM#14]
This might be a trivial question. After StatSTEM computes the ICL, it asks the user to select the local minimum. I am confused about which local minimum should be used at this point. For example, in fig. 7.2 in the manual, the local minima exists at 4, 6, and 10. However, the local minima at 10 is selected for the atom counting methodology. Why is it so?

**Comment by annickdebacker** [comment]
If more local minima are present, prior knowledge is needed to decide between the different minima. In the case of the Pt nanoparticle, we assume it is spherical. In this manner, the number of atoms along the 3rd dimension can be retrieved from the shape we observe in the projection (in combination with crystal structure and zone axis). If such prior knowledge is not available, calibrated experimental scattering cross-section need to be compared with simulated scattering cross-section values in order to decide between the different minima of the ICL. I hope this helps understanding the procedure for atom-counting.
