### ISSUE TITLE
error when doing fit model

### ISSUE THREAD

**Issue by TGfield** [quantitativeTEM/StatSTEM#34]
Dear professor:
   the software is very useful. there has some little problem when i first using.  I found that there is an error pops up immediately after starting the fitting routine:
   "Function error
   Error in script: averageDistance at line: 26
   Undefined function 'gcp' for input arguments of type 'char'."
Also, when i try the model selection(MAP), the another error shows:
   "Function error: 
    Error in script :optimset at line :147
    Default options not provided, function "isqnonlin" not present in path"

I use the last release of StatStem.
The Matlab version is R2020a.
Hope to get your reply !
Thanks

**Comment by bfhammel** [comment]
Hey TGfield. I also just started using StatSTEM and encountered the same issue. After some searching, I found out that first error occurs when the Parallel Computing Toolbox is not installed. I also found that a few other toolboxes are required, see quote below:

> It seems like you are missing required matlab toolboxes. You'll need the following add-ons:
> 
>     * distrib_computing_toolbox
> 
>     * image_toolbox
> 
>     * optimization_toolbox
> 
>     * statistics_toolbox
> 
> 
> You can install additional toolboxes under the "Apps"-Menu, then "Get more Apps" and find the toolboxes you need: ![image](https://user-images.githubusercontent.com/47680554/136963397-49ee524a-e688-4c9f-9bd8-2b82f0e8bffb.png)

Perhaps the second error is due to the optimization toolbox not being installed; hopefully installing all of the necessary toolboxes solves your problem.

Cheers,
Ben
