### ISSUE TITLE
some error occurs

### ISSUE THREAD

**Issue by jinsuoh** [quantitativeTEM/StatSTEM#6]
![roi error 2](https://user-images.githubusercontent.com/36701504/36483460-8158498c-1759-11e8-96bb-d336ad610009.png)

hi, I don't know why this error occurs. plz help me!! 
![default](https://user-images.githubusercontent.com/36701504/36483508-b113595a-1759-11e8-84ba-1a91824c0667.png)

**Comment by karelvandenbos** [comment]
Dear jinsuoh, 

We never saw this problem before, therefore, we don;t know directly how to solve this. 
Maybe it help if you put the number of CPU cores in parallel computing to 1?
Have you tried fitting with another option, for example the different width approach?

Best wishes,
Karel

**Comment by karelvandenbos** [comment]
Dear Jinsuoh, 

This should be a problem with parallel computing. As we never see this problem here, I cannot solve this issue. However, if you turn off parallel computing by putting the number of CPU cores to 1 (in the advanced options of the "fit model" panel) this issue should be solved.

Best wishes,
Karel
