### ISSUE TITLE
Problem Analysing if the number of gaussians is more than 100

### ISSUE THREAD

**Issue by Quantumstud** [quantitativeTEM/StatSTEM#8]
In my analysis, I am using a mixture of Gaussian model with more than 100 Gaussians. I am receiving the following error:
____
Error in script: Future.fetchOutputs at line :346
One or more futures resulted in an error
____
I suspected this to be a parallel computing error since StatSTEM works fine for less than 100 models.
Therefore, I tried changing the number of CPU cores to 1 but it automatically changes it back to 6.

**Comment by annickdebacker** [comment]
Thank you for using StatSTEM.

There is no limitation in the number of Gaussian components in a mixture model in the StatSTEM software.
I do not think that this is related to the parallel computing implementation, since this is related to the fitting of the Gaussian peaks to a 2-dimensional electron microscopy (EM) image, and not to the fitting of a Gaussian mixture model for atom-counting.  Normally you should be able to change the number of CPU cores by changing the number and pressing enter.

As an extra remark, I would like to mention that we never tested thoroughly the performance of our atom-counting method for columns thicker than 100 atoms in a columns. Therefore, we also do not know how reliable the Gaussian mixture model analysis is for more than 100 components.  The method was designed for counting the number of atoms in monotype-crystalline nanoparticles. When fitting a large number of components, one needs to take into account that the amount of analysed columns in a 2D EM image is also very high, in order to be able to fit all the components reliably. Maybe the amount of columns is not large enough.
