### ISSUE TITLE
errors in loading images

### ISSUE THREAD

**Issue by Stemmaker** [quantitativeTEM/StatSTEM#9]
Hello, I'm very interested in your StatSTEM, but I received the following errors when I started to load an image (.txt) :
Error using dlmread (line 147)
Mismatch between file and format character vector.
Trouble reading 'Numeric' field from file (row number 1, field number 1) ==> Database file for
StatSTEM\n
Error in loadTXTFile (line 19)
obs = dlmread(FileName);
Error in loadStatSTEMfile (line 51)
        [file,message] = loadTXTFile(FileName);
Error in loadFile
Error while evaluating UIControl Callback.
I seriously and sincerely hope to receive your reply, thanks

**Comment by annickdebacker** [comment]
Many thanks for your interest in using StatSTEM.
Do you have an original file format .dm3 or .ser? 
These file formats can be loaded easily into StatSTEM v 3.0.

I hope this helps.

**Comment by annickdebacker** [comment]
For the upper limit, you can choose a large enough values, which is suitable for most cases (e.g. 100). If you have some prior knowledge on the thickness of the particle, you can indeed modify the upper limit on the number of components for the ICL analysis to reduce the computation time. In order to do so, you need to know the structure (e.g. FCC for Au) and the orientation (e.g. 110). Then you know the distance between the atoms in the third dimension and you can determine the expected maximum number of atoms in this dimension from the expected thickness. Always take the upper limit for the ICL criterion a bit higher in order to be robust to some statistical variations due to the noise.
I give a more detailed example for roughly symmetrical particles. In this case, you count the number of atomic columns in projection in the a- and/or b- direction. For an FCC crystal in 110 orientation, you expect approximately the same number of atoms in the thickest column. For 100 orientation in an FCC structure, you expect then half of the number of atoms in the third dimension, as compared to the number of columns you have counted in projection.
If you have no prior knowledge on the thickness, the quality of the data should be very good in order to make an accurate interpretation of the minimum in the ICL criterion. In any case, a comparison of the normalised experimental intensities with simulated intensities, can help determining the thickness.

I hope this description gives you an idea how to decide on the upper limit on the number of components.

**Comment by Stemmaker** [comment]
Thanks a lot for your explicit explanation.
In addition, it is essential for obtaining a library of simulated scattering cross-sections to compare to the experimental values, and this file must be stored in a (n*1) vector. My problem is how to develop a (.mat) file of my data, could you give me an elegant procedure?

**Comment by annickdebacker** [comment]
The simulated scattering cross-section values need to be obtained using detailed image simulations (e.g. MULTEM - https://github.com/Ivanlh20/MULTEM/releases). The mat-file should contain a vector containing the SCS values as a function of the number of atoms. Such an example file is given in the example folder by the file Library_PtIr.mat.

**Comment by Stemmaker** [comment]
I have obtained a simple 3D model of my picture by using StatSTEM as it is so perfect and convenient for us to count atoms  of  the atomic column.I read your article(i.e. Nature470,374-377(2011)) in which the atom counting results  was used to obtained  a 3D model combined with discrete tomography , so is the raw codes of discrete tomography and simulated annealing algorithm freely available online? Maybe my request is a bit rash.
Thanks a lot!

**Comment by annickdebacker** [comment]
Discrete tomography and molecular dynamics simulations are not included in StatSTEM.

**Comment by Stemmaker** [comment]
Ok, thank you.
